### ISSUE TITLE
should we remove the `skimage` dependency?

### ISSUE THREAD

**Issue by tjlane** [rs-station/meteor#78]
This would require pulling Chambolle's algo out of `sklearn` and into `meteor`, which seems pretty easy. It means we will have to maintain that code (bad) but that we will have a simpler dependency tree (good). I actually soft-vote that we should not do this, but open to opinions @kmdalton and @alisiafadini .

**Comment by kmdalton** [comment]
I don't think I'm in favor of this move either.

**Comment by alisiafadini** [comment]
I agree: soft-vote on not to do this

**Comment by tjlane** [comment]
consensus -- if we need to ditch `sklearn` later, we know what to do
